/**
 * cmux-session.test.ts — shape/registration smoke for extensions/cmux-session.ts
 * Run: npx tsx extensions/cmux-session.test.ts
 *
 * The file is cmux-managed (regenerated by `cmux hooks pi install`); the repo
 * copy is a version-controlled snapshot for bootstrap. These tests pin the
 * minimal contract so a corrupted/regressed sync is caught: default factory
 * exists and registers the lifecycle handlers pi relies on.
 */
import { ok, equal } from "node:assert/strict";
import cmuxPiSessionExtension from "./cmux-session.js";

let passed = 0, failed = 0;
function test(name: string, fn: () => void) {
  try {
    fn();
    passed++;
    console.log(`  ✅ ${name}`);
  } catch (err: any) {
    failed++;
    console.log(`  ❌ ${name}: ${err.message}`);
  }
}

test("default export is a factory function", () => {
  equal(typeof cmuxPiSessionExtension, "function");
});

test("factory registers the lifecycle handlers pi relies on", () => {
  const handlers: Record<string, unknown> = {};
  const pi: any = { on: (ev: string, h: unknown) => { handlers[ev] = h; } };
  cmuxPiSessionExtension(pi);
  for (const ev of [
    "session_start",
    "before_agent_start",
    "tool_execution_start",
    "tool_execution_end",
    "agent_end",
    "agent_settled",
    "session_shutdown",
  ]) {
    ok(handlers[ev], `handler registered for ${ev}`);
  }
});

console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
