/**
 * task-heartbeat — child-side life-sign emitter for task-tool sub-agents (#176)
 *
 * Problem: the builtin-tools `task` tool watches the sub-agent's stdout/stderr
 * bytes and kills at the silence threshold. Pi in print mode buffers stdout
 * until the final turn, so a sub-agent that is ACTIVELY WORKING (long tool
 * call in flight, long model turn) emits zero bytes and gets killed mid-work
 * (recurrence of #129 at the 1800s threshold).
 *
 * Fix: this extension emits structured life signs on **stderr** (stdout is the
 * result payload; stderr flows unmediated in print mode and already resets the
 * parent's life-sign clock):
 *
 *   [task-heartbeat] ready nonce=<n>            — once at session_start
 *   [task-heartbeat] tool_start nonce=<n> <id> <name>   — tool_execution_start
 *   [task-heartbeat] tool_end nonce=<n> <id>            — tool_execution_end
 *   [task-heartbeat] turn_start nonce=<n> <n>           — turn_start
 *   [task-heartbeat] turn_end nonce=<n> <n>             — turn_end
 *   [task-heartbeat] tick nonce=<n> tools=<n> turn=<0|1> stream_age_ms=<n>
 *                       tool_age_max_ms=<n> tool_updates=<0|1>
 *                       cpu_ms=<n> cpu_stall_ms=<n> cpu_advanced=<0|1>
 *                       saw_msg=<0|1> saw_tool=<0|1>
 *                                               — every clamped interval
 *                                                     (#928 added cpu_ms /
 *                                                     cpu_stall_ms; see the
 *                                                     CPU-liveness block
 *                                                     below formatTick)
 *   [task-heartbeat] session_end nonce=<n>       — once at session_shutdown
 *                                                  (session completed — #191)
 *
 * The parent (builtin-tools spawnSubAgent) parses these markers into state
 * (tools in flight, turn active, stream age) and suppresses the silence kill
 * while life signs are fresh. When this extension is absent the parent falls
 * back to exact legacy byte-silence behavior — fully backward compatible.
 *
 * Gating: active only when TASK_HEARTBEAT=1 AND PI_MODE=print (both set by the
 * task tool for sub-agents) and NOT TASK_HEARTBEAT_DISABLE=1. Silent in
 * interactive sessions and other print-mode contexts (e.g. swarm_daemon).
 *
 * Authentication: every marker carries the per-dispatch nonce from
 * TASK_HEARTBEAT_NONCE (generated by the parent task tool per spawn). The
 * parent rejects markers without the matching nonce — MCP servers inherit the
 * child's fd 2 (MCP SDK stdio default stderr:"inherit") and could otherwise
 * inject forged life signs; an ambient TASK_HEARTBEAT=1 in a user's shell
 * can't produce the nonce either.
 *
 * Self-contained by default: only the ExtensionAPI type is imported (erased at
 * runtime, so tests can import this file without mocks). NOTE: flat extensions
 * CAN resolve ./shared/* (verified 2026-08-13; the #5611 sibling-import constraint
 * is stale for the current jiti/static loader).
 * runtime, so tests can import this file without mocks).
 *
 * Marker format is drift-guarded against the parent parser by E14 in
 * extensions/builtin-tools/builtin-tools.test.ts (round-trip + constant parity).
 *
 * ── Orphan watchdog (#385) ────────────────────────────────────────────────────
 * This extension ALSO carries the child-side parent-death watchdog: when the
 * orchestrator (parent pi) is SIGKILLed (macOS Jetsam or any cause), the child
 * reparents to PID 1 and every parent-side reaping path (settle-path pgid sweep,
 * treeKill, the 6h hard-cap timer, mcp-client's process.on("exit") transport kill)
 * dies with the parent — the orphan would accumulate forever, holding pi + MCP
 * memory. The watchdog makes cleanup parent-independent:
 *
 *   - gate: orphanWatchdogActive() = TASK_HEARTBEAT=1 AND PI_MODE=print AND
 *     ORPHAN_WATCHDOG != "0" — the repo's established sub-agent identity pair
 *     (verification-gate/review-enforcer isTaskSubAgent). DISABLE-agnostic:
 *     TASK_HEARTBEAT_DISABLE=1 (subagent-extension children) silences the
 *     EMITTER only, never the watchdog. Exempts swarm_daemon workers
 *     (PI_MODE=print only — no pair) and user one-shot `pi -p` runs.
 *   - detection: poll process.ppid (module-load scope, unref'd, zero exec —
 *     Node's ppid is dynamic and flips to 1 on reparenting, macOS-verified).
 *     Predicate: ppid !== originalPpid || ppid === 1 (subreaper + boot-race arms).
 *   - self-termination: double-confirm + min-uptime guards, then kill OWN
 *     descendant tree (MCP grandchildren, bash forks) TERM → grace → SIGKILL +
 *     a pgid catch-net, append a durable attribution line, exit(137). The
 *     mcp-client process.on("exit") transport kill runs as a second net.
 *   - safety valves: ORPHAN_WATCHDOG=0 (farm-wide opt-out), min-uptime +
 *     double-confirm (false-positive insurance), fired latch, NODE_ENV=test
 *     gated test hooks.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
// #385: shared process primitives — flat extensions CAN resolve ./shared/*
// (verified 2026-08-13). getChildPids/treeKill for the descendant kill,
// getPgid/listPgid for the pgid catch-net.
import { getChildPids, treeKill } from "./shared/tree-kill.js";
import { getPgid, listPgid } from "./shared/process-sweep.js";

// ── Marker contract (drift-guarded vs builtin-tools/index.ts — E14) ────

export const HEARTBEAT_MARKER_PREFIX = "[task-heartbeat]";

/** Tick interval clamp bounds — MUST match the parent's copy in
 * extensions/builtin-tools/index.ts (drift test E14). */
export const HEARTBEAT_INTERVAL_MIN_MS = 5_000;
export const HEARTBEAT_INTERVAL_MAX_MS = 300_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 30_000;

/** Clamp a raw interval value into [5s, 300s]. Non-finite/≤0 → default. */
export function clampHeartbeatIntervalMs(raw: number): number {
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_HEARTBEAT_INTERVAL_MS;
  return Math.min(HEARTBEAT_INTERVAL_MAX_MS, Math.max(HEARTBEAT_INTERVAL_MIN_MS, raw));
}

/** Resolve the tick interval from TASK_HEARTBEAT_INTERVAL_MS (default 30s). */
export function getHeartbeatIntervalMs(
  env: Record<string, string | undefined> = process.env,
): number {
  return clampHeartbeatIntervalMs(Number(env.TASK_HEARTBEAT_INTERVAL_MS));
}

/** Activation gate (exported for tests): TASK_HEARTBEAT=1 AND PI_MODE=print
 * AND not TASK_HEARTBEAT_DISABLE=1. */
export function taskHeartbeatActive(
  env: Record<string, string | undefined> = process.env,
): boolean {
  return (
    env.TASK_HEARTBEAT === "1" &&
    env.PI_MODE === "print" &&
    env.TASK_HEARTBEAT_DISABLE !== "1"
  );
}

// ── Marker formatters (one per kind; E14 round-trips them through the
//    parent parser so the full format — field names, argument order — is
//    drift-proof) ────────────────────────────────────────────────────────

export function formatReady(nonce: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} ready nonce=${nonce}`;
}

export function formatToolStart(nonce: string, toolCallId: string, toolName: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} tool_start nonce=${nonce} ${toolCallId} ${toolName}`;
}

export function formatToolEnd(nonce: string, toolCallId: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} tool_end nonce=${nonce} ${toolCallId}`;
}

export function formatTurnStart(nonce: string, turnIndex: number): string {
  return `${HEARTBEAT_MARKER_PREFIX} turn_start nonce=${nonce} ${turnIndex}`;
}

export function formatTurnEnd(nonce: string, turnIndex: number): string {
  return `${HEARTBEAT_MARKER_PREFIX} turn_end nonce=${nonce} ${turnIndex}`;
}

export interface TickFields {
  tools: number;
  turn: boolean;
  streamAgeMs: number;
  toolAgeMaxMs: number;
  sawMsg: boolean;
  sawTool: boolean;
  /** #783 §6.6: the in-flight tool round has emitted at least one update. */
  toolUpdates: boolean;
  /** #928: cumulative CPU (ms) of the in-flight tool's PROCESS SUBTREE.
   * 0 = not probed (no eligible tool, probe unavailable, or nothing found). */
  cpuMs: number;
  /** #928: wall-clock ms since `cpuMs` last INCREASED while an eligible tool
   * was in flight. 0 = not probed. See the CPU-liveness block below. */
  cpuStallMs: number;
  /** #928: TRUE iff this tool round has DEMONSTRATED CPU work — the probe has
   * observed at least one strict increase since the round's baseline. This is
   * what makes flat-CPU evidence admissible: a tool that has never burned any
   * CPU at all (an `npm ci` downloading, a `git fetch` on a slow link, any
   * I/O-bound command — all silent AND CPU-idle by nature) is NOT evidence of
   * a deadlock, and must never be killed on flat CPU alone. Mirrors clause 1's
   * philosophy exactly: only ever kill a tool that has demonstrated it works,
   * then stopped. */
  cpuAdvanced: boolean;
}

/** #783 §6.6: the output-liveness bit the tick carries — true iff there is at
 * least one in-flight tool and EVERY one of them has emitted at least one
 * `tool_execution_update`. UNIVERSAL, not existential: the parent uses this to
 * decide whether silence means "the silent tool is wedged", which is only sound
 * if the silence cannot belong to a tool that never emits at all (a nested
 * `task` — see E279a2). Exported so the direction is pinned by a unit test
 * rather than only by a handler closure. */
export function computeToolUpdates(
  outstanding: Iterable<string>,
  updated: ReadonlySet<string>,
): boolean {
  let any = false;
  for (const id of outstanding) {
    any = true;
    if (!updated.has(id)) return false;
  }
  return any;
}

export function formatTick(nonce: string, f: TickFields): string {
  return (
    `${HEARTBEAT_MARKER_PREFIX} tick nonce=${nonce} ` +
    `tools=${f.tools} turn=${f.turn ? 1 : 0} ` +
    `stream_age_ms=${f.streamAgeMs} tool_age_max_ms=${f.toolAgeMaxMs} ` +
    `tool_updates=${f.toolUpdates ? 1 : 0} ` +
    `cpu_ms=${f.cpuMs} cpu_stall_ms=${f.cpuStallMs} cpu_advanced=${f.cpuAdvanced ? 1 : 0} ` +
    `saw_msg=${f.sawMsg ? 1 : 0} saw_tool=${f.sawTool ? 1 : 0}`
  );
}

// ── #928: non-output liveness for a SILENT in-flight tool ──────────────
//
// The gap this closes. `stream_age_ms` is not a progress signal for a silent
// tool: every `tool_execution_update` feeds `touchActivity()`, so a tool that
// emits nothing leaves it on the same monotonic curve as a healthy nested
// `task`. That is why the parent's `toolUpdates` gate refuses to kill either —
// and why the ONLY bound left for a genuinely wedged silent tool is the
// multi-hour age backstop (4h by default). The two states the parent must
// separate are timing-IDENTICAL on every quantity the heartbeat carries today.
//
// The signal that does separate them is PROCESS LIVENESS. In the #928 incident
// the in-flight `grep` had accumulated 69m50s of CPU — genuinely working, just
// slowly. A deadlocked tool accumulates none. So the emitter reports the CPU
// time of the in-flight tool's process subtree and how long it has been flat.
//
// ── Why `cpu_advanced` exists (i.e. why flat CPU alone is not enough) ──
// CPU-flat has two causes: a DEADLOCK, and a legitimate I/O block. The second
// is common and healthy — a download, a slow query, a `git fetch` on a bad
// link all accrue ~no CPU for minutes while making real progress. Killing on
// flat CPU alone would therefore trade one false kill (the nested `task`) for
// another (the silent-but-downloading `bash`).
//
// The discriminator that IS available: a tool that has DEMONSTRATED CPU work
// in this round and THEN gone flat is a deadlock signature; a tool that has
// never burned CPU at all is just I/O-bound. So the emitter reports
// `cpu_advanced` alongside the sample, and the parent admits flat-CPU evidence
// only when it is true. This is the same shape as clause 1's rule — only kill a
// tool that has demonstrated it works and then stopped — applied to the CPU
// channel instead of the output channel.
//
// ── Why an ALLOWLIST, and why `task` is excluded ──
// CPU-flat is evidence of death ONLY for a tool whose progress is CPU-bound.
// A nested `task` legitimately sits at ~0 CPU for minutes while its child
// awaits a provider response, so probing it would re-create the E279a2 false
// kill this whole channel exists to avoid. An UNKNOWN tool is never probed
// either: a new tool kind must not acquire a kill path by accident. The
// allowlist is a NECESSARY narrowing condition, never the discriminator —
// `npm ci` and the wedged `grep` are both `bash`, and only the CPU sample
// separates them.
//
// ── Fail-safe direction ──
// Every failure mode (no eligible tool, `ps` unavailable, unparseable output,
// no descendants found) reports `cpu_stall_ms=0` — i.e. "not probed".
// Absence of evidence must never arm a kill; a parent that cannot prove a
// tool is dead must fall back to its existing bounds.

/** #928: tool names whose progress is CPU-bound and whose process subtree is
 * therefore meaningful to sample. Allowlist by design (see the block above):
 * an unlisted tool is never probed and can never acquire a kill path.
 * `task` is deliberately ABSENT — a nested sub-agent's quiet is legitimate. */
export const CPU_LIVENESS_TOOL_NAMES: ReadonlySet<string> = new Set(["bash"]);

/** #928: cap on the `ps` probe. The probe runs on the tick path, so it must
 * never be able to wedge the emitter. */
export const CPU_PROBE_TIMEOUT_MS = 2_000;

/** #928: parse one `ps -o time=` cell (cumulative CPU) into milliseconds.
 *
 * Two dialects, both observed in this repo's existing `ps` usage:
 *   macOS  `MM:SS.ss` (the minutes field is NOT clamped to 60 — `337:23.88`
 *                      is 337 minutes) and `HH:MM:SS`;
 *   Linux  `[[DD-]hh:]mm:ss` per procps.
 * The RIGHTMOST field is always seconds, so the parse is positional from the
 * right and both dialects fall out of the same loop.
 *
 * Returns null for anything unparseable (`-`, empty, a bare word) so the
 * caller can treat it as "not probed" rather than as zero CPU. */
export function parsePsCpuTimeMs(raw: string): number | null {
  const s = raw.trim();
  if (s === "" || s === "-") return null;
  const dash = s.indexOf("-");
  const days = dash >= 0 ? Number(s.slice(0, dash)) : 0;
  if (dash >= 0 && !Number.isFinite(days)) return null;
  const parts = (dash >= 0 ? s.slice(dash + 1) : s).split(":");
  // `parts.length === 0` cannot happen for a non-empty trimmed string ("".split
  // yields one element) and the empty case returned above — kept as
  // defence-in-depth so a refactor cannot turn it into a silent 0.
  if (parts.length === 0 || parts.length > 3) return null;
  const nums = parts.map((p) => Number(p));
  if (nums.some((n) => !Number.isFinite(n) || n < 0)) return null;
  let seconds = 0;
  for (const n of nums) seconds = seconds * 60 + n;
  return Math.round((days * 86_400 + seconds) * 1000);
}

/** #928: `ps -axo pid=,ppid=,pgid=,time=` output (one process per line).
 *
 * Returns `{ cpuMs, pgids }` — the summed CUMULATIVE CPU of the tool's tree and
 * the distinct detached process groups it spans (sorted) — or null when there
 * was nothing to measure. `pgids` exists so the CALLER can refuse an
 * unattributable measurement (see the note below). Never returns `{cpuMs: 0}` in place of null: a measured zero
 * and "nothing measured" must not be confused.
 *
 * Two filters, both load-bearing:
 *
 *  · `rootPid` itself is EXCLUDED — the child pi's own CPU advances on every
 *    tick (it is running this very probe), so including it would mask a dead
 *    tool permanently. Only the tool's tree is evidence.
 *
 *  · a descendant is counted only when its PROCESS GROUP differs from the
 *    root's. pi spawns the `bash` tool's shell `detached: true` (its own pgid —
 *    verified in the installed pi's bash tool), while its NON-tool children
 *    (MCP servers) are spawned non-detached and share pi's pgid. Without this
 *    filter a background MCP server accruing even a millisecond of CPU would
 *    advance the sample, and a genuinely deadlocked tool would never be
 *    detected — the probe would measure "is anything under pi busy" instead of
 *    "is THIS tool alive".
 *
 * ⚠️ The pgid filter alone does NOT attribute the measurement to a TOOL. Other
 * things pi spawns are detached too: a nested `task`/`subagent` child, and
 * `tortoise-capture`'s `python3`. Their CPU would otherwise be credited to
 * whichever eligible tool happens to be in flight, arming the dead-tool clause
 * against a tool that never burned a cycle of its own. That is why the groups
 * are reported (`pgids`) rather than folded into the sum — the caller refuses a
 * multi-group snapshot, and pins the ONE group it will trust.
 *
 * Returns null when no descendant row is present — "nothing to measure" must
 * read as not-probed, never as zero-CPU (which would arm a kill on the tick
 * after a tool's command exits but before its `tool_execution_end`). Also
 * returns null when the root is absent from the snapshot, since its pgid is
 * then unknown.
 *
 * Note that the sum can DECREASE between ticks: `ps` lists live processes
 * only, so a descendant that exits drops out. The caller handles that by
 * re-basing rather than by treating the drop as progress. */
export function sumDescendantCpuMs(
  psOutput: string,
  rootPid: number,
): { cpuMs: number; pgids: number[] } | null {
  const children = new Map<number, number[]>();
  const selfMs = new Map<number, number>();
  const pgidOf = new Map<number, number>();
  for (const line of psOutput.split("\n")) {
    const m = line.trim().match(/^(\d+)\s+(\d+)\s+(\d+)\s+(\S+)$/);
    if (!m) continue;
    const pid = Number(m[1]);
    const ppid = Number(m[2]);
    const ms = parsePsCpuTimeMs(m[4]);
    if (ms === null) continue;
    pgidOf.set(pid, Number(m[3]));
    const kids = children.get(ppid);
    if (kids) kids.push(pid);
    else children.set(ppid, [pid]);
    selfMs.set(pid, ms);
  }
  const rootPgid = pgidOf.get(rootPid);
  if (rootPgid === undefined) return null;
  let total = 0;
  let seen = 0;
  const detachedGroups = new Set<number>();
  const queue = [...(children.get(rootPid) ?? [])];
  const visited = new Set<number>();
  while (queue.length > 0) {
    const pid = queue.shift() as number;
    // Cycle guard: a pid in the list can never be its own ancestor, but the
    // ps snapshot is not atomic and a recycled pid could theoretically close
    // a loop. Never let a malformed snapshot spin here.
    if (visited.has(pid)) continue;
    visited.add(pid);
    // Walk THROUGH every descendant, but only COUNT the detached groups.
    for (const kid of children.get(pid) ?? []) queue.push(kid);
    const pgid = pgidOf.get(pid);
    if (pgid === undefined || pgid === rootPgid) continue;
    detachedGroups.add(pgid);
    const own = selfMs.get(pid);
    if (own !== undefined) {
      total += own;
      seen += 1;
    }
  }
  // `pgids` carries both facts the caller needs: how many groups there are
  // (`length`) and WHICH ones (`[0]`). A separate `trees` count was a second
  // spelling of `pgids.length`, and a redundant guard is a guard that can be
  // removed without a test noticing — the exact failure this review cycle
  // exists to avoid.
  return seen === 0
    ? null
    : { cpuMs: total, pgids: [...detachedGroups].sort((a, b) => a - b) };
}

/** #928: sample the CPU-liveness signal. Returns the tree's cumulative CPU in
 * ms and which detached groups it spans, or null when the probe could not produce
 * a measurement. Never throws. */
export function probeToolTreeCpu(
  rootPid: number = process.pid,
): { cpuMs: number; pgids: number[] } | null {
  try {
    const out = execSync("ps -axo pid=,ppid=,pgid=,time=", {
      encoding: "utf-8",
      timeout: CPU_PROBE_TIMEOUT_MS,
      stdio: ["ignore", "pipe", "ignore"],
    });
    return sumDescendantCpuMs(out, rootPid);
  } catch {
    return null;
  }
}

/** #928 test seam: replace the probe (e.g. to pin the clause WITHOUT spawning
 * `ps`). Mirrors `setLoad1Override` in extensions/builtin-tools/index.ts and
 * `orphanWatchdogHooks` below. Pass null to restore the real probe. */
let _cpuProbeOverride: (() => { cpuMs: number; pgids: number[] } | null) | null = null;
export function setCpuProbeOverride(fn: (() => { cpuMs: number; pgids: number[] } | null) | null): void {
  _cpuProbeOverride = fn;
}

/** #928: the CPU-liveness clock's state. Holds the baseline sample, the last
 * time the sample INCREASED, and whether the current round has demonstrated
 * CPU work at all. Kept as an exported pure reducer rather than a closure so
 * the advancement rule — the whole discriminator — is unit-testable without a
 * timer. (It was a closure first; a mutation of its `>` to `>=` left the entire
 * suite green while making the fix inert, which is exactly what an untestable
 * discriminator buys.) */
export interface CpuLiveness {
  /** false until a sample has been taken for the current eligible round. */
  baselineSet: boolean;
  lastSampleMs: number;
  lastAdvanceAt: number;
  /** Demonstrated CPU work this round — see `cpuAdvanced` in TickFields. */
  advanced: boolean;
  /** #928: the process group this round is measuring, pinned by the first
   * admitted sample. Later samples must see this group and only it — see the
   * identity-pin note in `sampleToolCpu`. null = not yet pinned. */
  pinnedPgid: number | null;
}

export function newCpuLiveness(): CpuLiveness {
  return { baselineSet: false, lastSampleMs: 0, lastAdvanceAt: 0, advanced: false, pinnedPgid: null };
}

/** #928: clear the EVIDENCE but keep the round's pinned group. Used wherever the
 * round has not changed but the measurement cannot be trusted this tick — a
 * failed probe, an unattributable snapshot, a different group appearing. The
 * pin must survive those, or the very next tick would simply re-pin to whatever
 * is now visible and adopt the foreign group the pin was there to refuse. */
export function clearCpuEvidence(s: CpuLiveness): void {
  s.baselineSet = false;
  s.advanced = false;
}

/** Re-arm for a NEW round: clears the evidence AND drops the pinned group, since
 * the next round is about a different tool. This is the round-boundary call —
 * tool_start / tool_end / turn_end — not the "unmeasurable this tick" call (see
 * `clearCpuEvidence`). */
export function resetCpuLiveness(s: CpuLiveness): void {
  clearCpuEvidence(s);
  s.pinnedPgid = null;
}

/** Advance the clock with one measurement and return the tick's fields. Pure
 * apart from mutating `s`. `sample === null` means NOT PROBED (probe failed,
 * `ps` unavailable, no descendant rows, or no eligible tool) and clears the
 * baseline AND the demonstrated-work latch — a signal that is not continuous
 * proves nothing.
 *
 * Advancing = the sample is STRICTLY GREATER than the previous one. A sample
 * that DROPS is a descendant exiting (`ps` lists live processes only); we
 * re-base to it without treating the drop as progress — but the stall clock is
 * only reset by a real INCREASE, so a drop can never extend the stall either.
 * The next genuine increase clears it. */
export function stepCpuLiveness(
  s: CpuLiveness,
  sample: number | null,
  now: number,
): { cpuMs: number; cpuStallMs: number; cpuAdvanced: boolean } {
  if (sample === null) {
    return { cpuMs: 0, cpuStallMs: 0, cpuAdvanced: s.advanced };
  }
  if (!s.baselineSet) {
    s.baselineSet = true;
    s.lastSampleMs = sample;
    s.lastAdvanceAt = now;
  } else if (sample > s.lastSampleMs) {
    s.lastSampleMs = sample;
    s.lastAdvanceAt = now;
    s.advanced = true;
  } else {
    s.lastSampleMs = sample;
  }
  return {
    cpuMs: sample,
    cpuStallMs: Math.max(0, now - s.lastAdvanceAt),
    cpuAdvanced: s.advanced,
  };
}

/** Completion marker (#191): the child declares the session complete. The
 * parent (builtin-tools) latches sessionEnded and arms a short exit grace
 * (TASK_EXIT_COMPLETE_GRACE_MS, default 15s) so a completed child stuck in
 * MCP disconnect cleanup is killed and its captured output returned as
 * success instead of hanging the parent tool call. */
export function formatSessionEnd(nonce: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} session_end nonce=${nonce}`;
}

// ── Orphan watchdog (#385) ───────────────────────────────────────────────
// Child-side parent-death detection: poll process.ppid (module-load scope,
// unref'd, zero exec — Node's ppid is dynamic and flips to 1 on reparenting,
// macOS-verified); on double-confirm + min-uptime, kill the OWN descendant
// tree (MCP grandchildren / bash forks) and exit(137). See the file header
// for the full contract. Test hooks are NODE_ENV=test-gated (#212 precedent).

export const ORPHAN_WATCHDOG_INTERVAL_MIN_MS = 5_000;
export const DEFAULT_ORPHAN_WATCHDOG_INTERVAL_MS = 15_000;
export const DEFAULT_ORPHAN_WATCHDOG_MIN_UPTIME_MS = 60_000;
export const ORPHAN_WATCHDOG_GRACE_MIN_MS = 1_000;
export const DEFAULT_ORPHAN_WATCHDOG_GRACE_MS = 4_000;
export const ORPHAN_WATCHDOG_LOG_PATH = path.join(os.homedir(), ".pi", "agent", "orphan-watchdog.log");

/** Poll interval: ORPHAN_WATCHDOG_INTERVAL_MS, default 15s, floor 5s. */
export function getOrphanIntervalMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_INTERVAL_MS);
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_ORPHAN_WATCHDOG_INTERVAL_MS;
  return Math.max(ORPHAN_WATCHDOG_INTERVAL_MIN_MS, raw);
}

/** Min-uptime guard: never self-terminate before this age (default 60s). */
export function getOrphanMinUptimeMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_MIN_UPTIME_MS);
  if (!Number.isFinite(raw) || raw < 0) return DEFAULT_ORPHAN_WATCHDOG_MIN_UPTIME_MS;
  return raw;
}

/** TERM→KILL grace between the descendant walks (default 4s, floor 1s). */
export function getOrphanGraceMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_GRACE_MS);
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_ORPHAN_WATCHDOG_GRACE_MS;
  return Math.max(ORPHAN_WATCHDOG_GRACE_MIN_MS, raw);
}

/** Watchdog gate — the repo's sub-agent identity pair + opt-out valve.
 * DISABLE-agnostic: TASK_HEARTBEAT_DISABLE=1 silences the emitter only.
 * Exempts swarm_daemon workers (PI_MODE=print only) and user one-shots. */
export function orphanWatchdogActive(env: Record<string, string | undefined> = process.env): boolean {
  return env.TASK_HEARTBEAT === "1" && env.PI_MODE === "print" && env.ORPHAN_WATCHDOG !== "0";
}

/** Orphan predicate: ppid CHANGED (reparented — covers Linux subreaper
 * adoption to a non-1 pid) OR ppid === 1 (launchd adoption on macOS; also the
 * boot-race arm where the parent died before this extension loaded). */
export function isOrphaned(ppid: number, originalPpid: number): boolean {
  return ppid !== originalPpid || ppid === 1;
}

export interface OrphanWatchdogHooks {
  ppidGetter: () => number;
  nowGetter: () => number;
  killDescendants: (graceMs: number) => Promise<void>;
  exitProcess: (code: number) => void;
  appendLog: (line: string) => void;
}

const defaultAppendLog = (line: string): void => {
  try {
    fs.appendFileSync(ORPHAN_WATCHDOG_LOG_PATH, `${line}\n`, "utf8");
  } catch {
    // best-effort — a log failure must never break the kill path
  }
};

/** Default descendant-kill orchestration: TERM direct children (treeKill
 * recurses children-first within each subtree — MCP grandchildren and bash
 * forks die), ref'd grace, SIGKILL survivors, then a pgid catch-net when the
 * child is its own pgid leader (detached spawn) — closes the mid-fork escape
 * (a descendant forked between the re-walk and exit). Never signals self. */
const defaultKillDescendants = async (graceMs: number): Promise<void> => {
  for (const childPid of getChildPids(process.pid)) treeKill(childPid, "SIGTERM");
  await new Promise((resolve) => setTimeout(resolve, graceMs));
  for (const childPid of getChildPids(process.pid)) treeKill(childPid, "SIGKILL");
  const ownPgid = getPgid(process.pid);
  if (ownPgid !== null && ownPgid === process.pid) {
    for (const member of listPgid(ownPgid)) {
      if (member !== process.pid) {
        try {
          process.kill(member, "SIGKILL");
        } catch {
          // ESRCH — already dead
        }
      }
    }
  }
};

/** Module-level test hooks — honored ONLY under NODE_ENV=test (#212
 * security-pass convention: review-enforcer _setRunGhOverride precedent). */
export const orphanWatchdogHooks: OrphanWatchdogHooks = {
  ppidGetter: () => process.ppid,
  nowGetter: () => Date.now(),
  killDescendants: defaultKillDescendants,
  exitProcess: ((code: number) => {
    process.exit(code);
  }) as (code: number) => void,
  appendLog: defaultAppendLog,
};

let watchdogArmed = false;

/** Test-only reset of the already-armed latch (NODE_ENV=test-gated per the
 * #212 security-pass convention). Each test arms a fresh watchdog. */
export function _resetWatchdogArmedForTests(): void {
  if (process.env.NODE_ENV === "test") watchdogArmed = false;
}

export interface OrphanWatchdogHandle {
  timer: ReturnType<typeof setInterval>;
  poll: () => void;
}

/** Arm the parent-death watchdog at module-load scope. Returns null when the
 * gate is off or the watchdog is already armed (pi's loader re-runs the
 * factory on ctx.reload()). The handle exposes {timer, poll} so tests can
 * assert unref + drive polls synchronously. */
export function armOrphanWatchdog(): OrphanWatchdogHandle | null {
  if (!orphanWatchdogActive()) return null;
  if (watchdogArmed) return null;
  watchdogArmed = true;

  const originalPpid = orphanWatchdogHooks.ppidGetter();
  const startedAt = orphanWatchdogHooks.nowGetter();
  let confirmCount = 0;
  let fired = false;

  const poll = (): void => {
    if (fired) return;
    const now = orphanWatchdogHooks.nowGetter();
    const cur = orphanWatchdogHooks.ppidGetter();
    if (isOrphaned(cur, originalPpid)) {
      confirmCount += 1;
      if (confirmCount >= 2 && now - startedAt >= getOrphanMinUptimeMs()) {
        fired = true;
        void fireSequence(originalPpid, cur, now - startedAt);
      }
    } else {
      confirmCount = 0;
    }
  };

  const timer = setInterval(poll, getOrphanIntervalMs());
  timer.unref?.();
  return { timer, poll };
}

/** Fire sequence: EPIPE-guarded stderr line + durable attribution append,
 * then kill the descendant tree (TERM → grace → SIGKILL + pgid catch-net)
 * and exit(137). try/finally: the exit ALWAYS runs even if an unanticipated
 * exception occurs mid-sequence. */
async function fireSequence(originalPpid: number, curPpid: number, uptimeMs: number): Promise<void> {
  // Capture the hook FUNCTIONS once — the sequence may be suspended across
  // awaits (grace sleep, killDescendants); a later hooks mutation/restore
  // (tests) must never swap the exit function under the running sequence.
  const killDescendants = orphanWatchdogHooks.killDescendants;
  const exitProcess = orphanWatchdogHooks.exitProcess;
  const appendLog = orphanWatchdogHooks.appendLog;
  const logLine = `[task-heartbeat] orphan_watchdog parent=${originalPpid} ppid=${curPpid} uptime_ms=${uptimeMs} pid=${process.pid} — self-terminating`;
  try {
    try {
      console.error(logLine);
    } catch {
      // stderr EPIPE to a dead parent surfaces as a silenced async 'error'
      // event (Node swallows it by default) — never break the kill path
    }
    appendLog(logLine);
    await killDescendants(getOrphanGraceMs());
  } catch {
    // An exception in the kill path must never prevent the exit — we are
    // self-terminating anyway. Swallow and fall through to the finally.
  } finally {
    exitProcess(137);
  }
}

// ── Extension ───────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  // #385: the orphan watchdog arms in EVERY dispatch child (identity pair),
  // even when the emitter is disabled (TASK_HEARTBEAT_DISABLE=1 — subagent-
  // extension children). Module-load scope: a child wedged before
  // session_start still self-terminates when its parent is killed.
  if (orphanWatchdogActive()) {
    armOrphanWatchdog();
  }
  if (!taskHeartbeatActive()) return;

  // Per-dispatch nonce set by the parent task tool — echoed in every marker so
  // the parent can reject foreign lines that happen to carry the prefix
  // (MCP server stderr inherits the child's fd 2; farm files are writable by
  // sub-agents). Empty nonce → parent treats markers as foreign → legacy.
  const nonce = process.env.TASK_HEARTBEAT_NONCE ?? "";

  // In-flight tools tracked as a Map keyed by toolCallId (NOT a bare counter:
  // pi emits tool_execution_start during preflight and tool_execution_end in
  // completion order — a preflight-started tool that is rejected/skipped could
  // desync a counter forever). Values carry the start timestamp for
  // tool_age_max_ms and the tool NAME: #928's CPU-liveness probe is per tool
  // KIND (see CPU_LIVENESS_TOOL_NAMES), so the emitter must know what is in
  // flight, not just how many.
  const outstandingTools = new Map<string, { startedAt: number; name: string }>();
  /** #783 §6.6: which in-flight tools have emitted `tool_execution_update`.
   * Only streaming tools emit updates — `bash` does, while `task`, `read`,
   * `edit`, `write` pass `_onUpdate` UNUSED. The tick reports whether EVERY
   * in-flight tool has emitted (see `computeToolUpdates`): the clause concludes
   * something about the tool that went quiet, so "SOME tool produced output" is
   * the wrong direction — with a bash that emitted and ended while a nested
   * task is still in flight, an existential latch stayed true and killed the
   * healthy nested child (the P1 the §6.6 verifier reproduced). Tracked per
   * toolCallId and dropped on end so the set cannot grow without bound. */
  const updatedToolIds = new Set<string>();
  let lastActivityAt = Date.now();
  let turnActive = false;
  let turnSawMessage = false;
  let turnSawTool = false;
  let tickTimer: ReturnType<typeof setInterval> | null = null;

  // #928 CPU-liveness state — the clock's mutable state, advanced by the pure
  // reducer `stepCpuLiveness` (exported so the advancement rule is pinned by
  // unit tests rather than only by the tick timer). `cpuMeasurementAttributable`
  // gates whether it is sampled at all; a reset re-arms the baseline so a new
  // eligible round earns its own evidence.
  const cpuLiveness = newCpuLiveness();

  const emit = (line: string) => {
    try {
      console.error(line);
    } catch {
      // never let the emitter break the sub-agent
    }
  };

  const touchActivity = () => {
    lastActivityAt = Date.now();
  };

  /** #928: the tool in flight, WHEN the measurement can be ATTRIBUTED to it.
   *
   * The probe enumerates pi's detached descendants, and pi spawns other things
   * detached besides the bash shell — a nested `task`/`subagent` child, and
   * `tortoise-capture`'s `python3`. Those are ineligible KINDS, so the allowlist
   * does not exclude them, and their CPU would be credited to whichever
   * eligible tool happens to be in flight: that would arm `cpu_advanced` for a
   * `bash` that never burned a cycle of its own and defeat the whole
   * "never kill an I/O-bound tool" guarantee (the exact bypass two independent
   * reviewers reproduced).
   *
   * So a sample is taken ONLY when it is attributable, and attribution is by
   * IDENTITY, not by count:
   *
   *   1. exactly ONE tool is in flight, and it is eligible;
   *   2. at the FIRST sample of a round, exactly ONE detached group exists —
   *      that group is pinned as THE tool's group for the rest of the round;
   *   3. every later sample of the round must see that same group.
   *
   * (2) alone would NOT be enough, and the gap is this round's own lifecycle:
   * when the `bash` shell EXITS, its group vanishes from `ps` while pi has not
   * yet emitted `tool_execution_end` (pi waits for the stdout/stderr pipes, and
   * re-arms a 100 ms idle timer on every chunk of output). If a foreign detached
   * group — a nested `task`, a `tortoise-capture` helper — is what remains, the
   * tree count is still 1 and a count-based check admits it: the foreign group's
   * CPU is credited to a tool whose own process is ALREADY GONE, arming the
   * evidence latch for it. Requiring the pinned group to still be present
   * refuses that snapshot, which is the correct answer — this tool can no longer
   * be measured, so it must not be judged.
   *
   * Residual, stated rather than hidden: TWO concurrent eligible `bash` tools go
   * INERT (the set is never exactly one eligible tool). A busy one therefore
   * masks a wedged one, because the clause declines to judge rather than judging
   * on a union it cannot split. That is the fail-open (missed-kill) direction. */
  const cpuMeasurementAttributable = () => {
    if (outstandingTools.size !== 1) return false;
    for (const t of outstandingTools.values()) {
      return CPU_LIVENESS_TOOL_NAMES.has(t.name);
    }
    return false;
  };

  /** #928: sample the in-flight tool's tree CPU and derive the tick fields.
   * Thin shell over the pure `stepCpuLiveness` — all the rule logic lives there
   * so it is unit-testable; this only decides whether to sample at all. */
  const sampleToolCpu = (now: number): { cpuMs: number; cpuStallMs: number; cpuAdvanced: boolean } => {
    const notProbed = { cpuMs: 0, cpuStallMs: 0, cpuAdvanced: false };
    if (!cpuMeasurementAttributable()) {
      // Same round, unmeasurable this tick (a second tool joined) — clear the
      // evidence, keep the pin.
      clearCpuEvidence(cpuLiveness);
      return notProbed;
    }
    const measured = (_cpuProbeOverride ?? probeToolTreeCpu)();
    // No measurement: delegate to the reducer's null branch so there is exactly
    // ONE definition of what "not probed" means (it clears the evidence and
    // leaves the pin — the round has not changed). Inlining a second copy here
    // is how the branch would drift, or fall out of use entirely.
    if (measured === null) return stepCpuLiveness(cpuLiveness, null, now);
    // More than one detached group means the tree we can see is not the
    // in-flight tool's alone — a concurrent nested `task`, a `tortoise-capture`
    // helper, or the tool's OWN daemonizing child (a command that calls
    // `setsid()`: the shell itself cannot, it is already a group leader, but its
    // children can). Not attributable → not probed this tick, so the clause
    // stays inert. Note `clearCpuEvidence`, not `reset`: the round has not
    // changed, so the pin (and the tool it identifies) must survive.
    //
    // This is load-bearing at the FIRST sample of a round and nowhere else —
    // later samples are covered by the pin comparison below, which refuses any
    // group other than the pinned one. Both are needed: without this, a round
    // whose very first snapshot spans two groups would PIN one of them, and
    // every later sample would look consistent with it.
    if (measured.pgids.length !== 1) {
      clearCpuEvidence(cpuLiveness);
      return notProbed;
    }
    // Identity pin (see the note above): the first admitted sample of a round
    // fixes WHICH group this round is about; later samples must see that same
    // group. A different group means the tool's own group is gone (its shell
    // exited — the exact window a count-based check gets wrong) or another
    // appeared mid-round. Both are unattributable, and the refusal must be
    // STICKY for the round: clearing the pin here would let the next tick simply
    // re-pin to the foreign group and adopt it.
    const pgid = measured.pgids[0];
    if (cpuLiveness.pinnedPgid !== null && cpuLiveness.pinnedPgid !== pgid) {
      clearCpuEvidence(cpuLiveness);
      return notProbed;
    }
    cpuLiveness.pinnedPgid = pgid;
    return stepCpuLiveness(cpuLiveness, measured.cpuMs, now);
  };

  const tick = () => {
    const now = Date.now();
    let toolAgeMaxMs = 0;
    for (const t of outstandingTools.values()) {
      const age = now - t.startedAt;
      if (age > toolAgeMaxMs) toolAgeMaxMs = age;
    }
    const cpu = sampleToolCpu(now);
    emit(
      formatTick(nonce, {
        tools: outstandingTools.size,
        turn: turnActive,
        streamAgeMs: now - lastActivityAt,
        toolAgeMaxMs,
        toolUpdates: computeToolUpdates(outstandingTools.keys(), updatedToolIds),
        cpuMs: cpu.cpuMs,
        cpuStallMs: cpu.cpuStallMs,
        cpuAdvanced: cpu.cpuAdvanced,
        sawMsg: turnSawMessage,
        sawTool: turnSawTool,
      }),
    );
  };

  pi.on("session_start", async () => {
    emit(formatReady(nonce));
    lastActivityAt = Date.now();
    if (tickTimer) clearInterval(tickTimer);
    tickTimer = setInterval(tick, getHeartbeatIntervalMs());
    // Must NEVER hold the event loop open — the #153 hang-on-exit class.
    tickTimer.unref?.();
  });

  // The session_shutdown hook is the completion edge (#191): pi emits this
  // event (reason "quit") from agent-session-runtime.dispose() during normal
  // print-mode teardown (verified against the installed pi:
  // dist/core/agent-session-runtime.js L288-294), so this is where the child
  // declares the session complete. The marker MUST go out first — it is what
  // lets the parent rescue a completed child stuck in cleanup (MCP disconnect
  // timeouts never drain the event loop) instead of hanging the tool call.
  // Ordering note (corrected, review #250 P2): print-mode ISSUES the final
  // stdout write in the try block (text-mode output after the prompt loop)
  // BEFORE the finally runs disposeRuntime() → session_shutdown — so the
  // parent's pipe receives stdout bytes FIRST, the marker SECOND, and the
  // process close LAST. The parent composes on close (after both), so the
  // ordering is safe by construction — no skew to manage.
  pi.on("session_shutdown", async () => {
    emit(formatSessionEnd(nonce));
    if (tickTimer) {
      clearInterval(tickTimer);
      tickTimer = null;
    }
  });

  pi.on("turn_start", async (event) => {
    turnActive = true;
    // Per-turn flags reset — feeds the parent's first-message backstop.
    turnSawMessage = false;
    turnSawTool = false;
    touchActivity();
    emit(formatTurnStart(nonce, event.turnIndex));
  });

  pi.on("turn_end", async (event) => {
    turnActive = false;
    // Pi guarantees all tools finalize before turn_end — clearing here bounds
    // any residual start/end desync to one turn (cycle-2 P1 fix).
    // #783 review: `updatedToolIds` MUST be cleared alongside its sibling Map.
    // The per-id delete in `tool_execution_end` is not sufficient on its own: if
    // a `tool_execution_end` is ever lost or skipped (the exact desync this
    // clear exists to bound), the streamed tool's id would survive into LATER
    // turns, and a subsequent non-streaming tool (a nested `task`, say) reusing
    // that same toolCallId — plausible for providers that emit positional ids
    // like `call_0` — would make `computeToolUpdates` report a tool that has
    // never emitted as live. The child would then tick `tool_updates=1` and the
    // parent's PRIMARY `tool-silence` clause would kill the healthy silent child
    // at S: the precise false-liveness direction this gate exists to close.
    outstandingTools.clear();
    updatedToolIds.clear();
    touchActivity();
    emit(formatTurnEnd(nonce, event.turnIndex));
  });

  pi.on("tool_execution_start", async (event) => {
    // #928: EVERY tool start re-arms the CPU-liveness clock. Two reasons, both
    // load-bearing:
    //   · a fresh tool must earn its own evidence — a new tool can never
    //     inherit the previous tool's demonstrated work or flat-CPU age;
    //   · `cpuMeasurementAttributable` requires the in-flight set to be exactly
    //     one eligible tool, so ANY second tool (of any kind) makes the next
    //     measurement unattributable — and a clock that straddled that boundary
    //     would resume against a different process set.
    // Unconditional, therefore — including the overlapping swap where the set
    // never empties (the case a `size === 0` gate misses). This is the fail-safe
    // direction: a spurious clear costs at most one tick. The parent clears its
    // own latches on every tool_start too.
    resetCpuLiveness(cpuLiveness);
    outstandingTools.set(event.toolCallId, {
      startedAt: Date.now(),
      name: event.toolName ?? "",
    });
    turnSawTool = true;
    touchActivity();
    emit(formatToolStart(nonce, event.toolCallId, event.toolName));
  });

  pi.on("tool_execution_update", async (event) => {
    updatedToolIds.add(event.toolCallId);
    touchActivity();
  });

  pi.on("tool_execution_end", async (event) => {
    outstandingTools.delete(event.toolCallId);
    updatedToolIds.delete(event.toolCallId);
    touchActivity();
    emit(formatToolEnd(nonce, event.toolCallId));
  });

  pi.on("message_start", async (event) => {
    // message_start fires for user/toolResult messages too — only assistant
    // responses count as stream activity.
    if ((event.message as { role?: string })?.role === "assistant") {
      turnSawMessage = true;
      touchActivity();
    }
  });

  pi.on("message_update", async () => {
    // Streaming token deltas — the primary stream-activity signal.
    turnSawMessage = true;
    touchActivity();
  });
}
