/**
 * task-heartbeat — child-side life-sign emitter for task-tool sub-agents (#176)
 *
 * Problem: the builtin-tools `task` tool watches the sub-agent's stdout/stderr
 * bytes and kills at the silence threshold. Pi in print mode buffers stdout
 * until the final turn, so a sub-agent that is ACTIVELY WORKING (long tool
 * call in flight, long model turn) emits zero bytes and gets killed mid-work
 * (recurrence of #129 at the 1800s threshold).
 *
 * Fix: this extension emits structured life signs on **stderr** (stdout is the
 * result payload; stderr flows unmediated in print mode and already resets the
 * parent's life-sign clock):
 *
 *   [task-heartbeat] ready nonce=<n>            — once at session_start
 *   [task-heartbeat] tool_start nonce=<n> <id> <name>   — tool_execution_start
 *   [task-heartbeat] tool_end nonce=<n> <id>            — tool_execution_end
 *   [task-heartbeat] turn_start nonce=<n> <n>           — turn_start
 *   [task-heartbeat] turn_end nonce=<n> <n>             — turn_end
 *   [task-heartbeat] tick nonce=<n> tools=<n> turn=<0|1> stream_age_ms=<n>
 *                       tool_age_max_ms=<n> saw_msg=<0|1> saw_tool=<0|1>
 *                                               — every clamped interval
 *   [task-heartbeat] session_end nonce=<n>       — once at session_shutdown
 *                                                  (session completed — #191)
 *
 * The parent (builtin-tools spawnSubAgent) parses these markers into state
 * (tools in flight, turn active, stream age) and suppresses the silence kill
 * while life signs are fresh. When this extension is absent the parent falls
 * back to exact legacy byte-silence behavior — fully backward compatible.
 *
 * Gating: active only when TASK_HEARTBEAT=1 AND PI_MODE=print (both set by the
 * task tool for sub-agents) and NOT TASK_HEARTBEAT_DISABLE=1. Silent in
 * interactive sessions and other print-mode contexts (e.g. swarm_daemon).
 *
 * Authentication: every marker carries the per-dispatch nonce from
 * TASK_HEARTBEAT_NONCE (generated by the parent task tool per spawn). The
 * parent rejects markers without the matching nonce — MCP servers inherit the
 * child's fd 2 (MCP SDK stdio default stderr:"inherit") and could otherwise
 * inject forged life signs; an ambient TASK_HEARTBEAT=1 in a user's shell
 * can't produce the nonce either.
 *
 * Self-contained by default: only the ExtensionAPI type is imported (erased at
 * runtime, so tests can import this file without mocks). NOTE: flat extensions
 * CAN resolve ./shared/* (verified 2026-08-13; the #5611 sibling-import constraint
 * is stale for the current jiti/static loader).
 * runtime, so tests can import this file without mocks).
 *
 * Marker format is drift-guarded against the parent parser by E14 in
 * extensions/builtin-tools/builtin-tools.test.ts (round-trip + constant parity).
 *
 * ── Orphan watchdog (#385) ────────────────────────────────────────────────────
 * This extension ALSO carries the child-side parent-death watchdog: when the
 * orchestrator (parent pi) is SIGKILLed (macOS Jetsam or any cause), the child
 * reparents to PID 1 and every parent-side reaping path (settle-path pgid sweep,
 * treeKill, the 6h hard-cap timer, mcp-client's process.on("exit") transport kill)
 * dies with the parent — the orphan would accumulate forever, holding pi + MCP
 * memory. The watchdog makes cleanup parent-independent:
 *
 *   - gate: orphanWatchdogActive() = TASK_HEARTBEAT=1 AND PI_MODE=print AND
 *     ORPHAN_WATCHDOG != "0" — the repo's established sub-agent identity pair
 *     (verification-gate/review-enforcer isTaskSubAgent). DISABLE-agnostic:
 *     TASK_HEARTBEAT_DISABLE=1 (subagent-extension children) silences the
 *     EMITTER only, never the watchdog. Exempts swarm_daemon workers
 *     (PI_MODE=print only — no pair) and user one-shot `pi -p` runs.
 *   - detection: poll process.ppid (module-load scope, unref'd, zero exec —
 *     Node's ppid is dynamic and flips to 1 on reparenting, macOS-verified).
 *     Predicate: ppid !== originalPpid || ppid === 1 (subreaper + boot-race arms).
 *   - self-termination: double-confirm + min-uptime guards, then kill OWN
 *     descendant tree (MCP grandchildren, bash forks) TERM → grace → SIGKILL +
 *     a pgid catch-net, append a durable attribution line, exit(137). The
 *     mcp-client process.on("exit") transport kill runs as a second net.
 *   - safety valves: ORPHAN_WATCHDOG=0 (farm-wide opt-out), min-uptime +
 *     double-confirm (false-positive insurance), fired latch, NODE_ENV=test
 *     gated test hooks.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
// #385: shared process primitives — flat extensions CAN resolve ./shared/*
// (verified 2026-08-13). getChildPids/treeKill for the descendant kill,
// getPgid/listPgid for the pgid catch-net.
import { getChildPids, treeKill } from "./shared/tree-kill.js";
import { getPgid, listPgid } from "./shared/process-sweep.js";

// ── Marker contract (drift-guarded vs builtin-tools/index.ts — E14) ────

export const HEARTBEAT_MARKER_PREFIX = "[task-heartbeat]";

/** Tick interval clamp bounds — MUST match the parent's copy in
 * extensions/builtin-tools/index.ts (drift test E14). */
export const HEARTBEAT_INTERVAL_MIN_MS = 5_000;
export const HEARTBEAT_INTERVAL_MAX_MS = 300_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 30_000;

/** Clamp a raw interval value into [5s, 300s]. Non-finite/≤0 → default. */
export function clampHeartbeatIntervalMs(raw: number): number {
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_HEARTBEAT_INTERVAL_MS;
  return Math.min(HEARTBEAT_INTERVAL_MAX_MS, Math.max(HEARTBEAT_INTERVAL_MIN_MS, raw));
}

/** Resolve the tick interval from TASK_HEARTBEAT_INTERVAL_MS (default 30s). */
export function getHeartbeatIntervalMs(
  env: Record<string, string | undefined> = process.env,
): number {
  return clampHeartbeatIntervalMs(Number(env.TASK_HEARTBEAT_INTERVAL_MS));
}

/** Activation gate (exported for tests): TASK_HEARTBEAT=1 AND PI_MODE=print
 * AND not TASK_HEARTBEAT_DISABLE=1. */
export function taskHeartbeatActive(
  env: Record<string, string | undefined> = process.env,
): boolean {
  return (
    env.TASK_HEARTBEAT === "1" &&
    env.PI_MODE === "print" &&
    env.TASK_HEARTBEAT_DISABLE !== "1"
  );
}

// ── Marker formatters (one per kind; E14 round-trips them through the
//    parent parser so the full format — field names, argument order — is
//    drift-proof) ────────────────────────────────────────────────────────

export function formatReady(nonce: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} ready nonce=${nonce}`;
}

export function formatToolStart(nonce: string, toolCallId: string, toolName: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} tool_start nonce=${nonce} ${toolCallId} ${toolName}`;
}

export function formatToolEnd(nonce: string, toolCallId: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} tool_end nonce=${nonce} ${toolCallId}`;
}

export function formatTurnStart(nonce: string, turnIndex: number): string {
  return `${HEARTBEAT_MARKER_PREFIX} turn_start nonce=${nonce} ${turnIndex}`;
}

export function formatTurnEnd(nonce: string, turnIndex: number): string {
  return `${HEARTBEAT_MARKER_PREFIX} turn_end nonce=${nonce} ${turnIndex}`;
}

export interface TickFields {
  tools: number;
  turn: boolean;
  streamAgeMs: number;
  toolAgeMaxMs: number;
  sawMsg: boolean;
  sawTool: boolean;
}

export function formatTick(nonce: string, f: TickFields): string {
  return (
    `${HEARTBEAT_MARKER_PREFIX} tick nonce=${nonce} ` +
    `tools=${f.tools} turn=${f.turn ? 1 : 0} ` +
    `stream_age_ms=${f.streamAgeMs} tool_age_max_ms=${f.toolAgeMaxMs} ` +
    `saw_msg=${f.sawMsg ? 1 : 0} saw_tool=${f.sawTool ? 1 : 0}`
  );
}

/** Completion marker (#191): the child declares the session complete. The
 * parent (builtin-tools) latches sessionEnded and arms a short exit grace
 * (TASK_EXIT_COMPLETE_GRACE_MS, default 15s) so a completed child stuck in
 * MCP disconnect cleanup is killed and its captured output returned as
 * success instead of hanging the parent tool call. */
export function formatSessionEnd(nonce: string): string {
  return `${HEARTBEAT_MARKER_PREFIX} session_end nonce=${nonce}`;
}

// ── Orphan watchdog (#385) ───────────────────────────────────────────────
// Child-side parent-death detection: poll process.ppid (module-load scope,
// unref'd, zero exec — Node's ppid is dynamic and flips to 1 on reparenting,
// macOS-verified); on double-confirm + min-uptime, kill the OWN descendant
// tree (MCP grandchildren / bash forks) and exit(137). See the file header
// for the full contract. Test hooks are NODE_ENV=test-gated (#212 precedent).

export const ORPHAN_WATCHDOG_INTERVAL_MIN_MS = 5_000;
export const DEFAULT_ORPHAN_WATCHDOG_INTERVAL_MS = 15_000;
export const DEFAULT_ORPHAN_WATCHDOG_MIN_UPTIME_MS = 60_000;
export const ORPHAN_WATCHDOG_GRACE_MIN_MS = 1_000;
export const DEFAULT_ORPHAN_WATCHDOG_GRACE_MS = 4_000;
export const ORPHAN_WATCHDOG_LOG_PATH = path.join(os.homedir(), ".pi", "agent", "orphan-watchdog.log");

/** Poll interval: ORPHAN_WATCHDOG_INTERVAL_MS, default 15s, floor 5s. */
export function getOrphanIntervalMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_INTERVAL_MS);
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_ORPHAN_WATCHDOG_INTERVAL_MS;
  return Math.max(ORPHAN_WATCHDOG_INTERVAL_MIN_MS, raw);
}

/** Min-uptime guard: never self-terminate before this age (default 60s). */
export function getOrphanMinUptimeMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_MIN_UPTIME_MS);
  if (!Number.isFinite(raw) || raw < 0) return DEFAULT_ORPHAN_WATCHDOG_MIN_UPTIME_MS;
  return raw;
}

/** TERM→KILL grace between the descendant walks (default 4s, floor 1s). */
export function getOrphanGraceMs(env: Record<string, string | undefined> = process.env): number {
  const raw = Number(env.ORPHAN_WATCHDOG_GRACE_MS);
  if (!Number.isFinite(raw) || raw <= 0) return DEFAULT_ORPHAN_WATCHDOG_GRACE_MS;
  return Math.max(ORPHAN_WATCHDOG_GRACE_MIN_MS, raw);
}

/** Watchdog gate — the repo's sub-agent identity pair + opt-out valve.
 * DISABLE-agnostic: TASK_HEARTBEAT_DISABLE=1 silences the emitter only.
 * Exempts swarm_daemon workers (PI_MODE=print only) and user one-shots. */
export function orphanWatchdogActive(env: Record<string, string | undefined> = process.env): boolean {
  return env.TASK_HEARTBEAT === "1" && env.PI_MODE === "print" && env.ORPHAN_WATCHDOG !== "0";
}

/** Orphan predicate: ppid CHANGED (reparented — covers Linux subreaper
 * adoption to a non-1 pid) OR ppid === 1 (launchd adoption on macOS; also the
 * boot-race arm where the parent died before this extension loaded). */
export function isOrphaned(ppid: number, originalPpid: number): boolean {
  return ppid !== originalPpid || ppid === 1;
}

export interface OrphanWatchdogHooks {
  ppidGetter: () => number;
  nowGetter: () => number;
  killDescendants: (graceMs: number) => Promise<void>;
  exitProcess: (code: number) => void;
  appendLog: (line: string) => void;
}

const defaultAppendLog = (line: string): void => {
  try {
    fs.appendFileSync(ORPHAN_WATCHDOG_LOG_PATH, `${line}\n`, "utf8");
  } catch {
    // best-effort — a log failure must never break the kill path
  }
};

/** Default descendant-kill orchestration: TERM direct children (treeKill
 * recurses children-first within each subtree — MCP grandchildren and bash
 * forks die), ref'd grace, SIGKILL survivors, then a pgid catch-net when the
 * child is its own pgid leader (detached spawn) — closes the mid-fork escape
 * (a descendant forked between the re-walk and exit). Never signals self. */
const defaultKillDescendants = async (graceMs: number): Promise<void> => {
  for (const childPid of getChildPids(process.pid)) treeKill(childPid, "SIGTERM");
  await new Promise((resolve) => setTimeout(resolve, graceMs));
  for (const childPid of getChildPids(process.pid)) treeKill(childPid, "SIGKILL");
  const ownPgid = getPgid(process.pid);
  if (ownPgid !== null && ownPgid === process.pid) {
    for (const member of listPgid(ownPgid)) {
      if (member !== process.pid) {
        try {
          process.kill(member, "SIGKILL");
        } catch {
          // ESRCH — already dead
        }
      }
    }
  }
};

/** Module-level test hooks — honored ONLY under NODE_ENV=test (#212
 * security-pass convention: review-enforcer _setRunGhOverride precedent). */
export const orphanWatchdogHooks: OrphanWatchdogHooks = {
  ppidGetter: () => process.ppid,
  nowGetter: () => Date.now(),
  killDescendants: defaultKillDescendants,
  exitProcess: ((code: number) => {
    process.exit(code);
  }) as (code: number) => void,
  appendLog: defaultAppendLog,
};

let watchdogArmed = false;

/** Test-only reset of the already-armed latch (NODE_ENV=test-gated per the
 * #212 security-pass convention). Each test arms a fresh watchdog. */
export function _resetWatchdogArmedForTests(): void {
  if (process.env.NODE_ENV === "test") watchdogArmed = false;
}

export interface OrphanWatchdogHandle {
  timer: ReturnType<typeof setInterval>;
  poll: () => void;
}

/** Arm the parent-death watchdog at module-load scope. Returns null when the
 * gate is off or the watchdog is already armed (pi's loader re-runs the
 * factory on ctx.reload()). The handle exposes {timer, poll} so tests can
 * assert unref + drive polls synchronously. */
export function armOrphanWatchdog(): OrphanWatchdogHandle | null {
  if (!orphanWatchdogActive()) return null;
  if (watchdogArmed) return null;
  watchdogArmed = true;

  const originalPpid = orphanWatchdogHooks.ppidGetter();
  const startedAt = orphanWatchdogHooks.nowGetter();
  let confirmCount = 0;
  let fired = false;

  const poll = (): void => {
    if (fired) return;
    const now = orphanWatchdogHooks.nowGetter();
    const cur = orphanWatchdogHooks.ppidGetter();
    if (isOrphaned(cur, originalPpid)) {
      confirmCount += 1;
      if (confirmCount >= 2 && now - startedAt >= getOrphanMinUptimeMs()) {
        fired = true;
        void fireSequence(originalPpid, cur, now - startedAt);
      }
    } else {
      confirmCount = 0;
    }
  };

  const timer = setInterval(poll, getOrphanIntervalMs());
  timer.unref?.();
  return { timer, poll };
}

/** Fire sequence: EPIPE-guarded stderr line + durable attribution append,
 * then kill the descendant tree (TERM → grace → SIGKILL + pgid catch-net)
 * and exit(137). try/finally: the exit ALWAYS runs even if an unanticipated
 * exception occurs mid-sequence. */
async function fireSequence(originalPpid: number, curPpid: number, uptimeMs: number): Promise<void> {
  // Capture the hook FUNCTIONS once — the sequence may be suspended across
  // awaits (grace sleep, killDescendants); a later hooks mutation/restore
  // (tests) must never swap the exit function under the running sequence.
  const killDescendants = orphanWatchdogHooks.killDescendants;
  const exitProcess = orphanWatchdogHooks.exitProcess;
  const appendLog = orphanWatchdogHooks.appendLog;
  const logLine = `[task-heartbeat] orphan_watchdog parent=${originalPpid} ppid=${curPpid} uptime_ms=${uptimeMs} pid=${process.pid} — self-terminating`;
  try {
    try {
      console.error(logLine);
    } catch {
      // stderr EPIPE to a dead parent surfaces as a silenced async 'error'
      // event (Node swallows it by default) — never break the kill path
    }
    appendLog(logLine);
    await killDescendants(getOrphanGraceMs());
  } catch {
    // An exception in the kill path must never prevent the exit — we are
    // self-terminating anyway. Swallow and fall through to the finally.
  } finally {
    exitProcess(137);
  }
}

// ── Extension ───────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  // #385: the orphan watchdog arms in EVERY dispatch child (identity pair),
  // even when the emitter is disabled (TASK_HEARTBEAT_DISABLE=1 — subagent-
  // extension children). Module-load scope: a child wedged before
  // session_start still self-terminates when its parent is killed.
  if (orphanWatchdogActive()) {
    armOrphanWatchdog();
  }
  if (!taskHeartbeatActive()) return;

  // Per-dispatch nonce set by the parent task tool — echoed in every marker so
  // the parent can reject foreign lines that happen to carry the prefix
  // (MCP server stderr inherits the child's fd 2; farm files are writable by
  // sub-agents). Empty nonce → parent treats markers as foreign → legacy.
  const nonce = process.env.TASK_HEARTBEAT_NONCE ?? "";

  // In-flight tools tracked as a Map keyed by toolCallId (NOT a bare counter:
  // pi emits tool_execution_start during preflight and tool_execution_end in
  // completion order — a preflight-started tool that is rejected/skipped could
  // desync a counter forever). Values are start timestamps for tool_age_max_ms.
  const outstandingTools = new Map<string, number>();
  let lastActivityAt = Date.now();
  let turnActive = false;
  let turnSawMessage = false;
  let turnSawTool = false;
  let tickTimer: ReturnType<typeof setInterval> | null = null;

  const emit = (line: string) => {
    try {
      console.error(line);
    } catch {
      // never let the emitter break the sub-agent
    }
  };

  const touchActivity = () => {
    lastActivityAt = Date.now();
  };

  const tick = () => {
    const now = Date.now();
    let toolAgeMaxMs = 0;
    for (const startedAt of outstandingTools.values()) {
      const age = now - startedAt;
      if (age > toolAgeMaxMs) toolAgeMaxMs = age;
    }
    emit(
      formatTick(nonce, {
        tools: outstandingTools.size,
        turn: turnActive,
        streamAgeMs: now - lastActivityAt,
        toolAgeMaxMs,
        sawMsg: turnSawMessage,
        sawTool: turnSawTool,
      }),
    );
  };

  pi.on("session_start", async () => {
    emit(formatReady(nonce));
    lastActivityAt = Date.now();
    if (tickTimer) clearInterval(tickTimer);
    tickTimer = setInterval(tick, getHeartbeatIntervalMs());
    // Must NEVER hold the event loop open — the #153 hang-on-exit class.
    tickTimer.unref?.();
  });

  // The session_shutdown hook is the completion edge (#191): pi emits this
  // event (reason "quit") from agent-session-runtime.dispose() during normal
  // print-mode teardown (verified against the installed pi:
  // dist/core/agent-session-runtime.js L288-294), so this is where the child
  // declares the session complete. The marker MUST go out first — it is what
  // lets the parent rescue a completed child stuck in cleanup (MCP disconnect
  // timeouts never drain the event loop) instead of hanging the tool call.
  // Ordering note (corrected, review #250 P2): print-mode ISSUES the final
  // stdout write in the try block (text-mode output after the prompt loop)
  // BEFORE the finally runs disposeRuntime() → session_shutdown — so the
  // parent's pipe receives stdout bytes FIRST, the marker SECOND, and the
  // process close LAST. The parent composes on close (after both), so the
  // ordering is safe by construction — no skew to manage.
  pi.on("session_shutdown", async () => {
    emit(formatSessionEnd(nonce));
    if (tickTimer) {
      clearInterval(tickTimer);
      tickTimer = null;
    }
  });

  pi.on("turn_start", async (event) => {
    turnActive = true;
    // Per-turn flags reset — feeds the parent's first-message backstop.
    turnSawMessage = false;
    turnSawTool = false;
    touchActivity();
    emit(formatTurnStart(nonce, event.turnIndex));
  });

  pi.on("turn_end", async (event) => {
    turnActive = false;
    // Pi guarantees all tools finalize before turn_end — clearing here bounds
    // any residual start/end desync to one turn (cycle-2 P1 fix).
    outstandingTools.clear();
    touchActivity();
    emit(formatTurnEnd(nonce, event.turnIndex));
  });

  pi.on("tool_execution_start", async (event) => {
    outstandingTools.set(event.toolCallId, Date.now());
    turnSawTool = true;
    touchActivity();
    emit(formatToolStart(nonce, event.toolCallId, event.toolName));
  });

  pi.on("tool_execution_update", async () => {
    touchActivity();
  });

  pi.on("tool_execution_end", async (event) => {
    outstandingTools.delete(event.toolCallId);
    touchActivity();
    emit(formatToolEnd(nonce, event.toolCallId));
  });

  pi.on("message_start", async (event) => {
    // message_start fires for user/toolResult messages too — only assistant
    // responses count as stream activity.
    if ((event.message as { role?: string })?.role === "assistant") {
      turnSawMessage = true;
      touchActivity();
    }
  });

  pi.on("message_update", async () => {
    // Streaming token deltas — the primary stream-activity signal.
    turnSawMessage = true;
    touchActivity();
  });
}
